### ISSUE TITLE
No hostname file created 

### ISSUE THREAD

**Issue by jakbin** [altermarkive/ssh-over-tor#1]
I check in $PWD directory , but there is no tor service files or any hostname file is there .

**Comment by altermarkive** [comment]
Hi! Does the `$PWD/tor` directory exist? If not then you'll need to create it prior to running the container.

**Comment by jakbin** [comment]
Yes , $PWD/tor directory exists.

**Comment by jakbin** [comment]
And I also check inside container .

**Comment by altermarkive** [comment]
Could you please share some screenshots or console listing - otherwise I have nothing to work with.
